spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none   # ← ★重要
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always     # ← ★これを入れないと MySQL では動かない